# Generated by Django 4.2.23 on 2026-03-06 23:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zettrack_app', '0004_attendance_latitude_in_attendance_latitude_out_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('total_days', models.PositiveIntegerField(default=12)),
                ('carry_forward', models.BooleanField(default=False)),
                ('description', models.TextField(blank=True)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_types', to='zettrack_app.company')),
            ],
        ),
        migrations.AddField(
            model_name='leaverequest',
            name='leave_type_obj',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='zettrack_app.leavetype'),
        ),
    ]
