# Generated by Django 4.2.23 on 2026-03-06 23:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zettrack_app', '0005_leavetype_leaverequest_leave_type_obj'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('total_days', models.DecimalField(decimal_places=2, max_digits=5)),
                ('used_days', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('leave_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='zettrack_app.leavetype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leave_balances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('user', 'leave_type', 'year')},
            },
        ),
    ]
