# Generated by Django 4.2.23 on 2026-03-07 00:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zettrack_app', '0006_userleavebalance'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeavePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('max_leaves_per_year', models.PositiveIntegerField(default=30)),
                ('accrual_policy', models.CharField(choices=[('Monthly', 'Monthly'), ('Yearly', 'Yearly')], default='Monthly', max_length=100)),
                ('carry_forward_limit', models.PositiveIntegerField(default=5)),
                ('approval_workflow', models.CharField(choices=[('Single Level', 'Single Level'), ('Multi Level', 'Multi Level')], default='Single Level', max_length=100)),
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='leave_policy', to='zettrack_app.company')),
            ],
        ),
    ]
