# Generated by Django 4.2.23 on 2026-03-10 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zettrack_app', '0009_publicholiday'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='company_logos/'),
        ),
    ]
