from django.contrib import admin
from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from zettrack_app import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index, name='index'),
    path('features/', views.features_view, name='features'),
    path('about/', views.about_view, name='about'),
    path('contact/', views.contact_view, name='contact'),
    path('how-to-use/', views.how_to_use_view, name='how_to_use'),
    path('pricing/', views.pricing_view, name='pricing'),
    path('signup/', views.signup_view, name='signup'),
    path('employee-signup/', views.employee_signup_view, name='employee_signup'),
    path('login/', views.login_view, name='login'),
    path('dashboard/', views.dashboard_redirect, name='dashboard'),
    path('dashboard/admin/', views.admin_dashboard, name='admin_dashboard'),
    path('dashboard/admin/employees/', views.employee_list_view, name='employee_list'),
    path('dashboard/admin/employees/add/', views.add_employee_view, name='add_employee'),
    path('dashboard/admin/employees/edit/<int:employee_id>/', views.edit_employee_view, name='edit_employee'),
    path('dashboard/admin/employees/<int:employee_id>/', views.employee_detail_view, name='employee_detail'),
    path('dashboard/admin/employees/delete/<int:employee_id>/', views.delete_employee_view, name='delete_employee'),
    path('dashboard/admin/attendance/', views.attendance_list_view, name='admin_attendance'),
    path('dashboard/admin/regularizations/', views.regularization_requests_view, name='admin_regularizations'),
    path('dashboard/employee/regularizations/', views.regularization_requests_view, name='my_regularizations'),
    path('dashboard/employee/regularizations/apply/', views.apply_regularization, name='apply_regularization'),
    path('dashboard/employee/', views.employee_dashboard, name='employee_dashboard'),
    path('dashboard/employee/profile/', views.employee_profile, name='employee_profile'),
    path('dashboard/employee/holidays/', views.employee_holidays, name='employee_holidays'),
    path('dashboard/admin/employees/import/', views.import_employees, name='import_employees'),
    path('dashboard/admin/employees/import/template/', views.download_employee_template, name='download_employee_template'),
    path('punch-in/', views.punch_in, name='punch_in'),
    path('punch-out/', views.punch_out, name='punch_out'),
    path('leave/apply/', views.leave_apply, name='leave_apply'),
    path('payslips/', views.payslips_view, name='payslips'),
    path('dashboard/admin/attendance/', views.attendance_list_admin, name='attendance_list_admin'),
    path('dashboard/admin/late-arrivals/', views.admin_late_arrivals, name='admin_late_arrivals'),
    path('dashboard/admin/present-today/', views.admin_present_today, name='admin_present_today'),
    path('dashboard/admin/absent-today/', views.admin_absent_today, name='admin_absent_today'),
    path('dashboard/admin/on-leave-today/', views.admin_on_leave_today, name='admin_on_leave_today'),
    path('dashboard/admin/regularization/', views.regularization_list_admin, name='regularization_list_admin'),
    path('dashboard/admin/regularization/<int:request_id>/<str:status>/', views.approve_regularization, name='approve_regularization'),
    path('attendance/calendar/', views.attendance_calendar_employee, name='attendance_calendar_employee'),
    path('attendance/regularize/', views.regularization_request_view, name='regularization_request'),
    path('dashboard/admin/attendance/mark/', views.mark_attendance_view, name='mark_attendance'),
    path('dashboard/admin/attendance/export/excel/', views.export_attendance_excel, name='export_attendance_excel'),
    path('dashboard/admin/attendance/export/pdf/', views.export_attendance_pdf, name='export_attendance_pdf'),
    path('dashboard/admin/payroll/', views.admin_payroll_dashboard, name='admin_payroll'),
    path('dashboard/admin/payroll/export/excel/', views.export_payroll_excel, name='export_payroll_excel'),
    path('dashboard/admin/payroll/export/pdf/', views.export_payroll_pdf, name='export_payroll_pdf'),
    path('dashboard/admin/payroll/payslip/<int:payroll_id>/pdf/', views.export_payslip_pdf, name='export_payslip_pdf'),
    path('dashboard/admin/notifications/', views.admin_notifications, name='admin_notifications'),
    path('dashboard/admin/leaves/', views.admin_leave_dashboard, name='admin_leaves'),
    path('dashboard/admin/leaves/approve/<int:leave_id>/', views.approve_leave, name='approve_leave'),
    path('dashboard/admin/leaves/reject/<int:leave_id>/', views.reject_leave, name='reject_leave'),
    path('dashboard/admin/leaves/types/add/', views.add_leave_type, name='add_leave_type'),
    path('dashboard/admin/leaves/types/edit/<int:type_id>/', views.edit_leave_type, name='edit_leave_type'),
    path('dashboard/admin/leaves/types/delete/<int:type_id>/', views.delete_leave_type, name='delete_leave_type'),
    path('dashboard/admin/leaves/balance/adjust/<int:bal_id>/', views.adjust_leave_balance, name='adjust_leave_balance'),
    path('dashboard/admin/leaves/balance/add-extra/<int:bal_id>/', views.add_extra_leave, name='add_extra_leave'),
    path('dashboard/admin/leaves/balance/reset/<int:bal_id>/', views.reset_leave_balance, name='reset_leave_balance'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/admin/departments/', views.department_list_view, name='department_list'),
    path('dashboard/admin/departments/add/', views.add_department_view, name='add_department'),
    path('dashboard/admin/departments/edit/<int:dept_id>/', views.edit_department_view, name='edit_department'),
    path('dashboard/admin/departments/delete/<int:dept_id>/', views.delete_department_view, name='delete_department'),
    path('dashboard/admin/departments/employees/', views.department_employees_view, name='department_employees'),
    path('dashboard/admin/departments/reports/', views.department_reports_view, name='department_reports'),
    path('dashboard/admin/designations/', views.designation_list_view, name='designation_list'),
    path('dashboard/admin/designations/add/', views.add_designation_view, name='add_designation'),
    path('dashboard/admin/designations/edit/<int:desig_id>/', views.edit_designation_view, name='edit_designation'),
    path('dashboard/admin/designations/delete/<int:desig_id>/', views.delete_designation_view, name='delete_designation'),
    path('dashboard/admin/designations/employees/', views.designation_employees_view, name='designation_employees'),
    path('dashboard/admin/designations/hierarchy/', views.designation_hierarchy_view, name='designation_hierarchy'),
    path('dashboard/admin/designations/reports/', views.designation_reports_view, name='designation_reports'),
    path('dashboard/admin/reports/attendance/', views.report_attendance, name='report_attendance'),
    path('dashboard/admin/reports/payroll/', views.report_payroll, name='report_payroll'),
    path('dashboard/admin/reports/employees/', views.report_employees, name='report_employees'),
    path('dashboard/admin/reports/leaves/', views.report_leaves, name='report_leaves'),
    path('dashboard/admin/reports/departments/', views.report_departments, name='report_departments'),
    path('dashboard/admin/reports/custom/', views.report_custom, name='report_custom'),
    path('dashboard/notifications/', views.notification_dashboard, name='notification_dashboard'),
    path('dashboard/notifications/mark-read/<int:notif_id>/', views.mark_notification_read, name='mark_notification_read'),
    path('dashboard/notifications/mark-all-read/', views.mark_all_notifications_read, name='mark_all_notifications_read'),
    path('dashboard/notifications/get-unread/', views.get_unread_notifications, name='get_unread_notifications'),
    path('dashboard/notifications/delete/<int:notif_id>/', views.delete_notification, name='delete_notification'),
    path('dashboard/notifications/settings/', views.notification_settings_view, name='notification_settings'),
    path('dashboard/admin/notifications/send-announcement/', views.send_announcement, name='send_announcement'),
    path('dashboard/admin/payroll/process-all/', views.process_payroll_all, name='process_payroll_all'),
    path('dashboard/admin/profile/', views.admin_profile_edit, name='admin_profile_edit'),
    path('dashboard/admin/regularization/<int:request_id>/edit/', views.admin_edit_regularization, name='admin_edit_regularization'),
    path('dashboard/admin/attendance/edit/<int:employee_id>/<str:attendance_date>/', views.admin_edit_attendance, name='admin_edit_attendance'),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
